### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by davidvargash** [whyleee/nuget-node-tools#1]
Hi

im getting this error when using Bower 1.3.11 in cmd

This version of C:\packages\node.js.0.10.28\node.exe is not compatible with windows version

Im using
-Visual Studi 2013 Express for the web
-Windows 7 Professional SP1 32 bits

I appreciate your help

**Comment by whyleee** [comment]
Node.js nuget package only supports Windows x64 versions, because NuGet doesn't have a good out-of-box solution to deliver different files for x32/x64 systems.

**Comment by davidvargash** [comment]
mmm i see thanks a lot for your answer
