### ISSUE TITLE
How can I help upgrading this to Node.js 5.3.0?

### ISSUE THREAD

**Issue by ffMathy** [whyleee/nuget-node-tools#2]
Hi there.

Can we upgrade this library or NuGet package to Node.js 5.3.0?
I assume it is the package found here: https://www.nuget.org/packages/Node.js/

It would help a lot. Would love to do it, but I have no idea of how to start.

Thanks in advance.

**Comment by whyleee** [comment]
@ffMathy I upgraded Node.js package to 5.3.0: https://www.nuget.org/packages/Node.js/.

**Comment by ffMathy** [comment]
Niiice! Does this mean it includes NPM 3 as well, and is it invokeable through Visual Studio?

**Comment by whyleee** [comment]
Nope, npm comes in a separate package. I'll try to update it today. Node and npm can be invoked in command-line as usual. NuGet packages are created generally to easily deploy these tools to servers without installation access. VS 2015 has out-of-box integration to npm and bower.

**Comment by ffMathy** [comment]
The thing is that the out-of-the-box version of NPM in Visual Studio is version 2.X, which doesn't include the new flat dependency directory feature.

**Comment by whyleee** [comment]
I published latest Npm 2.14.14 and 3.5.2 packages to NuGet: https://www.nuget.org/packages/Npm/

**Comment by FritzHerbers** [comment]
I have VS 2015 and installed both node and npm via nuget manager. 
What do i have to change to make the nuget version of npm activ?
